
# This is the standard visualization tool based on OpenGL
/vis/open OGLSX
/vis/viewer/set/viewpointThetaPhi -45 45
/vis/viewer/zoom 2.
/vis/viewer/set/projection perspective
/vis/viewer/set/lightsMove camera
/vis/drawVolume
/tracking/storeTrajectory 1
/vis/scene/add/trajectories
#/vis/scene/endOfEventAction accumulate -1
/vis/scene/add/axes 
/vis/scene/add/hits
#/vis/viewer/set/auxiliaryEdge 1
#/vis/geometry/set/forceSolid
#/vis/viewer/set/lineSegmentsPerCircle 200